apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-acme
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /.well-known/acme-challenge/
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: acme-challenge
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/.well-known/acme-challenge/`)
      kind: Rule
      priority: 100
      services:
        - name: traefik
          port: 8080
      middlewares:
        - name: strip-prefix-acme
          namespace: default
