apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: express
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create a directory for the Express server
          mkdir -p /app
          cd /app
          
          # Create package.json
          echo '{
            "name": "vibecode-express",
            "version": "1.0.0",
            "description": "Express server for GitHub OAuth callback",
            "main": "index.js",
            "dependencies": {
              "express": "^4.18.2",
              "axios": "^1.6.7",
              "cors": "^2.8.5"
            }
          }' > package.json
          
          # Create index.js
          echo 'const express = require("express");
          const axios = require("axios");
          const cors = require("cors");
          const app = express();
          const port = process.env.PORT || 5000;

          // Enable CORS for all routes with detailed logging
          app.use((req, res, next) => {
            console.log(`Incoming request: ${req.method} ${req.url}`);
            console.log(`Origin: ${req.headers.origin || "No origin"}`);
            console.log(`Headers: ${JSON.stringify(req.headers)}`);
            
            // Set CORS headers
            res.header("Access-Control-Allow-Origin", "*");
            res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
            res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
            
            // Handle preflight requests
            if (req.method === "OPTIONS") {
              console.log("Handling OPTIONS preflight request");
              return res.status(200).end();
            }
            
            next();
          });

          console.log("Starting Express server with GitHub OAuth support...");

          // Simple route
          app.get("/", (req, res) => {
            res.send("Express server is running");
          });

          // Health check endpoint
          app.get("/health", (req, res) => {
            res.status(200).send("OK");
          });

          // GitHub exchange route - path expected by frontend
          app.get("/api/auth/github/exchange", async (req, res) => {
            const code = req.query.code;
            
            console.log(`GitHub exchange request received with code: ${code}`);
            console.log(`Full URL: ${req.protocol}://${req.get("host")}${req.originalUrl}`);
            console.log(`Headers: ${JSON.stringify(req.headers)}`);
            
            if (!code) {
              console.error("No code parameter provided");
              return res.status(400).json({ error: "Code parameter is required" });
            }
            
            try {
              // Exchange code for access token with GitHub
              console.log("Exchanging code for access token with GitHub");
              console.log(`GitHub Client ID: ${process.env.GITHUB_CLIENT_ID}`);
              console.log(`GitHub Client Secret: ${process.env.GITHUB_CLIENT_SECRET ? "Set (hidden)" : "Not set"}`);
              
              const tokenResponse = await axios.post(
                "https://github.com/login/oauth/access_token",
                {
                  client_id: process.env.GITHUB_CLIENT_ID,
                  client_secret: process.env.GITHUB_CLIENT_SECRET,
                  code: code
                },
                {
                  headers: {
                    Accept: "application/json"
                  }
                }
              );
              
              console.log("Token response received from GitHub");
              const data = tokenResponse.data;
              
              if (data.error) {
                console.error(`GitHub error: ${data.error}`);
                return res.status(400).json({ error: `GitHub error: ${data.error}` });
              }
              
              if (!data.access_token) {
                console.error("No access token received from GitHub");
                return res.status(400).json({ error: "No access token received from GitHub" });
              }
              
              console.log("Successfully obtained GitHub access token");
              
              // Get user data from GitHub
              console.log("Getting user data from GitHub");
              const userResponse = await axios.get("https://api.github.com/user", {
                headers: {
                  Authorization: `token ${data.access_token}`
                }
              });
              
              const githubUser = userResponse.data;
              console.log(`GitHub user data received: ${JSON.stringify(githubUser, null, 2)}`);
              
              // Get user email
              console.log("Getting user email from GitHub");
              const emailsResponse = await axios.get("https://api.github.com/user/emails", {
                headers: {
                  Authorization: `token ${data.access_token}`
                }
              });
              
              const emails = emailsResponse.data;
              const primaryEmail = emails.find(email => email.primary);
              
              if (!primaryEmail) {
                console.error("No primary email found for GitHub user");
                return res.status(400).json({ error: "No primary email found for GitHub user" });
              }
              
              // Create user object
              const user = {
                username: githubUser.login,
                email: primaryEmail.email,
                full_name: githubUser.name || "",
                github_id: githubUser.id.toString(),
                avatar_url: githubUser.avatar_url
              };
              
              console.log(`User data: ${JSON.stringify(user, null, 2)}`);
              
              // Create a simple JWT token (in a real app, use a proper JWT library)
              const token = Buffer.from(JSON.stringify({ 
                sub: user.username,
                exp: Math.floor(Date.now() / 1000) + (60 * 60) // 1 hour expiration
              })).toString("base64");
              
              // Return user data and token
              console.log("Returning user data and token to frontend");
              const responseData = {
                access_token: token,
                token_type: "bearer",
                user: {
                  username: user.username,
                  email: user.email,
                  full_name: user.full_name,
                  avatar_url: user.avatar_url
                }
              };
              console.log(`Response data: ${JSON.stringify(responseData, null, 2)}`);
              return res.json(responseData);
              
            } catch (error) {
              console.error("Error processing GitHub exchange:", error.message);
              if (error.response) {
                console.error("Response data:", error.response.data);
                console.error("Response status:", error.response.status);
                console.error("Response headers:", error.response.headers);
              }
              return res.status(500).json({ 
                error: "Failed to authenticate with GitHub",
                details: error.message
              });
            }
          });

          // Start the server
          app.listen(port, "0.0.0.0", () => {
            console.log(`Server running on port ${port}`);
            console.log(`GitHub Client ID: ${process.env.GITHUB_CLIENT_ID || "Not set"}`);
            console.log(`GitHub Client Secret: ${process.env.GITHUB_CLIENT_SECRET ? "Set (hidden)" : "Not set"}`);
            console.log(`GitHub Redirect URI: ${process.env.GITHUB_REDIRECT_URI || "Not set"}`);
          });

          // Keep the process alive
          setInterval(() => {
            console.log("Express server is still running...");
          }, 60000);' > index.js
          
          # Install dependencies
          npm install
          
          # Start the Express server
          node index.js
        ports:
        - containerPort: 5000
        env:
        - name: GITHUB_CLIENT_ID
          value: "Iv23liWkm8qUlFlLAXKe"
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth-secret
              key: GITHUB_CLIENT_SECRET
        - name: GITHUB_REDIRECT_URI
          value: "https://vibecode.gigahard.ai/github-callback"
