apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: vibecode
    meta.helm.sh/release-namespace: vibecode
  creationTimestamp: "2025-04-13T23:45:08Z"
  generation: 2
  labels:
    app.kubernetes.io/instance: vibecode
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vibecode
    app.kubernetes.io/version: 1.0.0
    helm.sh/chart: vibecode-0.1.0
  name: express
  namespace: vibecode
  resourceVersion: "279578"
  uid: 15c2a2ab-92ab-40a6-bb12-db44212b9f9f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: express
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: express
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "5000"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_ID
              name: vibecode-github-oauth
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: GITHUB_CLIENT_SECRET
              name: vibecode-github-oauth
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: vibecode-github-oauth
        - name: GITHUB_REDIRECT_URI
          value: https://vibecode.gigahard.ai/github-callback
        image: gigahard/vibecode-express:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: express
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-04-14T00:18:48Z"
    lastUpdateTime: "2025-04-14T00:18:48Z"
    message: ReplicaSet "express-c7f96f89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-04-14T00:33:09Z"
    lastUpdateTime: "2025-04-14T00:33:09Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
