apiVersion: v1
kind: ConfigMap
metadata:
  name: express-server-files
  namespace: vibecode
data:
  "package.json": |
    {
      "name": "vibecode-express",
      "version": "1.0.0",
      "description": "Simple Express server for GitHub OAuth callback",
      "main": "index.js",
      "dependencies": {
        "express": "^4.18.2"
      }
    }
  "index.js": |
    // Minimal Express server
    const express = require('express');
    const app = express();
    const port = process.env.PORT || 5000;

    console.log('Starting minimal Express server...');

    // Simple route
    app.get('/', (req, res) => {
      res.send('Express server is running');
    });

    // Health check endpoint
    app.get('/health', (req, res) => {
      res.status(200).send('OK');
    });

    // GitHub callback route
    app.get('/api/express/auth/github/callback', (req, res) => {
      const code = req.query.code || 'no-code';
      console.log(`GitHub callback received with code: ${code}`);
      
      res.json({ 
        message: 'GitHub callback received',
        code: code,
        timestamp: new Date().toISOString()
      });
    });

    // Start the server
    app.listen(port, '0.0.0.0', () => {
      console.log(`Server running on port ${port}`);
    });

    // Keep the process alive
    process.stdin.resume();

    // Handle process termination
    process.on('SIGINT', () => {
      console.log('Received SIGINT. Exiting gracefully.');
      process.exit(0);
    });

    process.on('SIGTERM', () => {
      console.log('Received SIGTERM. Exiting gracefully.');
      process.exit(0);
    });
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-github-server
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-github-server
  template:
    metadata:
      labels:
        app: express-github-server
    spec:
      containers:
      - name: express
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          cd /app
          npm install
          node index.js
        ports:
        - containerPort: 5000
        env:
        - name: GITHUB_CLIENT_ID
          value: "Iv23liWkm8qUlFlLAXKe"
        - name: GITHUB_REDIRECT_URI
          value: "https://vibecode.gigahard.ai/github-callback"
        volumeMounts:
        - name: express-server-files
          mountPath: /app
      volumes:
      - name: express-server-files
        configMap:
          name: express-server-files
---
apiVersion: v1
kind: Service
metadata:
  name: express-github-server
  namespace: vibecode
spec:
  selector:
    app: express-github-server
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-github-server-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /api/express
        pathType: Prefix
        backend:
          service:
            name: express-github-server
            port:
              number: 5000
