apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: express
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create a directory for the Express server
          mkdir -p /app
          cd /app
          
          # Create package.json
          echo '{
            "name": "vibecode-express",
            "version": "1.0.0",
            "description": "Simple Express server for GitHub OAuth callback",
            "main": "index.js",
            "dependencies": {
              "express": "^4.18.2"
            }
          }' > package.json
          
          # Create index.js
          echo 'const express = require("express");
          const app = express();
          const port = process.env.PORT || 5000;

          console.log("Starting minimal Express server...");

          // Simple route
          app.get("/", (req, res) => {
            res.send("Express server is running");
          });

          // Health check endpoint
          app.get("/health", (req, res) => {
            res.status(200).send("OK");
          });

          // GitHub callback route
          app.get("/api/express/auth/github/callback", (req, res) => {
            const code = req.query.code || "no-code";
            console.log(`GitHub callback received with code: ${code}`);
            
            res.json({ 
              message: "GitHub callback received",
              code: code,
              timestamp: new Date().toISOString()
            });
          });

          // Start the server
          app.listen(port, "0.0.0.0", () => {
            console.log(`Server running on port ${port}`);
          });

          // Keep the process alive
          setInterval(() => {
            console.log("Express server is still running...");
          }, 60000);' > index.js
          
          # Install dependencies
          npm install
          
          # Start the Express server
          node index.js
        ports:
        - containerPort: 5000
        env:
        - name: GITHUB_CLIENT_ID
          value: "Iv23liWkm8qUlFlLAXKe"
        - name: GITHUB_REDIRECT_URI
          value: "https://vibecode.gigahard.ai/github-callback"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-express
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-express-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /api/express
        pathType: Prefix
        backend:
          service:
            name: simple-express
            port:
              number: 5000
