apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vibecode
  labels:
    app.kubernetes.io/instance: vibecode
    app.kubernetes.io/name: vibecode
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
