apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-injector-fix
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-injector-fix
  template:
    metadata:
      labels:
        app: frontend-injector-fix
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-injector-fix-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-injector-fix-config
  namespace: vibecode
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            # Proxy requests to the frontend
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Inject the script into the HTML
            sub_filter '</head>' '<script src="/fix.js"></script></head>';
            sub_filter_once on;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-injector-fix
  namespace: vibecode
spec:
  selector:
    app: frontend-injector-fix
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-injector-fix-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "500"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-injector-fix
            port:
              number: 80
