apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vibecode
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: inject-script
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create a backup of the original index.html
          cp /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak
          
          # Inject the override script before the closing </body> tag
          sed -i 's|</body>|<script src="/override-script.js"></script></body>|g' /usr/share/nginx/html/index.html
          
          echo "Script injected into index.html"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: override-script
          mountPath: /override-script.js
          subPath: override-script.js
      containers:
      - name: vibecode-frontend
        image: gigahard/vibecode-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 80
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: VITE_GITHUB_CLIENT_ID
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: VITE_API_URL
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: VITE_API_URL
        - name: VITE_GITHUB_CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: VITE_GITHUB_CALLBACK_URL
        - name: VITE_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: frontend-env
              key: VITE_BACKEND_URL
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: override-script
          mountPath: /usr/share/nginx/html/override-script.js
          subPath: override-script.js
      volumes:
      - name: html
        emptyDir: {}
      - name: override-script
        configMap:
          name: frontend-override
