apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-patch-final
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-patch-final
  template:
    metadata:
      labels:
        app: frontend-patch-final
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: patch-script
          mountPath: /usr/share/nginx/html/patch.js
          subPath: patch.js
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-patch-final-config
      - name: patch-script
        configMap:
          name: frontend-patch-final-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-patch-final-config
  namespace: vibecode
data:
  default.conf: |
    server {
        listen 80;
        
        location / {
            # Proxy requests to the frontend
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Inject the script into the HTML
            sub_filter '</head>' '<script src="/patch.js"></script></head>';
            sub_filter_once on;
        }
        
        location /patch.js {
            root /usr/share/nginx/html;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-patch-final-script
  namespace: vibecode
data:
  patch.js: |
    (function() {
      console.log("Fetch override script loaded");
      
      // Save the original fetch function
      const originalFetch = window.fetch;
      
      // Override the fetch function
      window.fetch = function(url, options) {
        // Check if the URL is the hardcoded localhost URL
        if (typeof url === "string" && url.includes("localhost:8000/api/auth/github/exchange")) {
          console.log("Intercepting fetch to localhost:8000");
          
          // Extract the code from the URL
          const originalUrl = new URL(url);
          const code = originalUrl.searchParams.get("code");
          
          // Create the new URL with the correct domain
          const newUrl = "https://vibecode.gigahard.ai/api/auth/github/exchange?code=" + code;
          console.log("Redirecting to: " + newUrl);
          
          // Call the original fetch with the new URL
          return originalFetch(newUrl, options);
        }
        
        // For all other URLs, use the original fetch
        return originalFetch.apply(this, arguments);
      };
      
      console.log("Fetch override installed");
    })();
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-patch-final
  namespace: vibecode
spec:
  selector:
    app: frontend-patch-final
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-patch-final-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "1000"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-patch-final
            port:
              number: 80
