apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-injector-config
  namespace: vibecode
data:
  default.conf: |
    server {
        listen 80;
        
        # Proxy requests to the frontend
        location / {
            # Enable CORS
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
            
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Inject the script into the HTML
            sub_filter '</head>' '<script src="/inject.js"></script></head>';
            sub_filter_once on;
        }
    }
