apiVersion: v1
kind: Service
metadata:
  name: localhost-service-direct-fix
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - port: 8000
    targetPort: 5000
  type: LoadBalancer
  externalIPs:
  - 127.0.0.1
