apiVersion: v1
kind: Service
metadata:
  name: localhost-service-direct-fix2
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - port: 8000
    targetPort: 5000
    nodePort: 30080
  type: NodePort
