apiVersion: v1
kind: Service
metadata:
  name: localhost-service-direct-fix8
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - name: http
    port: 8000
    targetPort: 5000
  type: ClusterIP
