apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localhost-redirect
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "500"
    traefik.ingress.kubernetes.io/router.middlewares: vibecode-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - localhost
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-8000
            port:
              number: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: vibecode
spec:
  redirectRegex:
    regex: ^http://localhost:8000/(.*)
    replacement: https://vibecode.gigahard.ai/$1
