apiVersion: v1
kind: Service
metadata:
  name: localhost-service-direct-fix10
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - name: http
    port: 8000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localhost-service-direct-fix10-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "900"
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: localhost-service-direct-fix10
            port:
              name: http
