apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: localhost-service-direct-fix7-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "700"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - localhost
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: localhost-8000-direct
            port:
              number: 8000
