apiVersion: v1
kind: Service
metadata:
  name: simple-express-service
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-express-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "200"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /api/auth/github/exchange
        pathType: Exact
        backend:
          service:
            name: simple-express-service
            port:
              number: 5000
