apiVersion: v1
kind: Service
metadata:
  name: localhost-8000
  namespace: default
spec:
  type: ExternalName
  externalName: simple-express-service.vibecode.svc.cluster.local
  ports:
  - port: 8000
    targetPort: 5000
