apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-projects-simple
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-projects-simple
  template:
    metadata:
      labels:
        app: mock-projects-simple
    spec:
      containers:
      - name: mock-projects-simple
        image: gigahard/mock-projects-simple:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mock-projects-simple
  namespace: vibecode
spec:
  selector:
    app: mock-projects-simple
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mock-projects-simple-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-https@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "1000000"  # Extremely high priority
spec:
  ingressClassName: traefik
  rules:
  - host: 0192.ai
    http:
      paths:
      - path: /api/projects
        pathType: Prefix
        backend:
          service:
            name: mock-projects-simple
            port:
              number: 80
