apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: vibecode
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;

            # Add JavaScript to override the fetch function
            sub_filter '</body>' '<script>
            // This script overrides the fetch function to intercept calls to localhost:8000
            (function() {
              console.log("GitHub callback URL override script loaded");

              // Save the original fetch function
              const originalFetch = window.fetch;

              // Override the fetch function
              window.fetch = function(url, options) {
                // Check if the URL is the hardcoded localhost URL
                if (typeof url === "string" && url.includes("localhost:8000/api/auth/github/exchange")) {
                  console.log("Intercepting fetch to localhost:8000");

                  // Extract the code from the URL
                  const originalUrl = new URL(url);
                  const codeParam = originalUrl.searchParams.get("code");

                  // Create the new URL with the correct domain
                  const newUrl = "https://vibecode.gigahard.ai/api/auth/github/exchange?code=" + codeParam;
                  console.log(`Redirecting to: ${newUrl}`);

                  // Call the original fetch with the new URL
                  return originalFetch(newUrl, options);
                }

                // For all other URLs, use the original fetch
                return originalFetch.apply(this, arguments);
              };

              console.log("Fetch override installed");
            })();
            </script></body>';
            sub_filter_once on;
        }

        # Proxy requests to the API
        location /api/ {
            proxy_pass http://simple-express:5000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
