apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-server
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script-server
  template:
    metadata:
      labels:
        app: script-server
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: script
          mountPath: /usr/share/nginx/html/inject.js
          subPath: inject.js
      volumes:
      - name: script
        configMap:
          name: frontend-script
---
apiVersion: v1
kind: Service
metadata:
  name: script-server
  namespace: vibecode
spec:
  selector:
    app: script-server
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: script-server-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.priority: "300"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vibecode.gigahard.ai
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /inject.js
        pathType: Exact
        backend:
          service:
            name: script-server
            port:
              number: 80
