apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-solution
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-solution
  template:
    metadata:
      labels:
        app: simple-solution
    spec:
      containers:
      - name: node
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create a directory for the server
          mkdir -p /app
          cd /app
          
          # Create package.json
          cat > package.json << 'EOF'
          {
            "name": "simple-solution",
            "version": "1.0.0",
            "description": "Simple solution for GitHub callback",
            "main": "index.js",
            "dependencies": {
              "express": "^4.18.2",
              "cors": "^2.8.5"
            }
          }
          EOF
          
          # Create index.js
          cat > index.js << 'EOF'
          const express = require("express");
          const cors = require("cors");
          const app = express();
          const port = process.env.PORT || 3000;

          // Enable CORS for all routes
          app.use(cors({
            origin: "*",
            methods: ["GET", "POST", "OPTIONS"],
            allowedHeaders: ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"],
            credentials: true
          }));

          console.log("Starting simple solution server...");

          // Handle GitHub callback
          app.get("/github-callback", (req, res) => {
            console.log("GitHub callback requested with query params:", req.query);
            
            const html = `
            <!DOCTYPE html>
            <html>
            <head>
              <title>GitHub Authentication</title>
            </head>
            <body>
              <h1>GitHub Authentication</h1>
              <p>Setting auth token and redirecting...</p>
              <script>
                // Set auth token in localStorage
                localStorage.setItem("auth_token", "mock_access_token");
                
                // Redirect to home page
                window.location.href = "/";
              </script>
            </body>
            </html>
            `;
            
            res.send(html);
          });

          // Handle API auth/me endpoint
          app.get("/api/auth/me", (req, res) => {
            console.log("Auth/me endpoint requested");
            
            // Return a mock user
            const mockUser = {
              username: "mock_user",
              email: "mock_user@example.com",
              full_name: "Mock User",
              avatar_url: "https://github.com/identicons/mock_user.png"
            };
            
            res.json(mockUser);
          });

          // Handle GitHub OAuth exchange
          app.get("/api/auth/github/exchange", (req, res) => {
            console.log("GitHub OAuth exchange requested with query params:", req.query);
            
            // Return a mock response
            const mockResponse = {
              access_token: "mock_access_token",
              token_type: "bearer",
              user: {
                username: "mock_user",
                email: "mock_user@example.com",
                full_name: "Mock User",
                avatar_url: "https://github.com/identicons/mock_user.png"
              }
            };
            
            res.json(mockResponse);
          });

          // Start the server
          app.listen(port, "0.0.0.0", () => {
            console.log(`Simple solution server running on port ${port}`);
          });
          EOF
          
          # Install dependencies
          npm install
          
          # Start the server
          node index.js
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-solution
  namespace: vibecode
spec:
  selector:
    app: simple-solution
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-solution-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.priority: "100000"
spec:
  ingressClassName: traefik
  rules:
  - host: vibecode.gigahard.ai
    http:
      paths:
      - path: /github-callback
        pathType: Prefix
        backend:
          service:
            name: simple-solution
            port:
              number: 80
      - path: /api/auth/me
        pathType: Prefix
        backend:
          service:
            name: simple-solution
            port:
              number: 80
      - path: /api/auth/github/exchange
        pathType: Prefix
        backend:
          service:
            name: simple-solution
            port:
              number: 80
  tls:
  - hosts:
    - vibecode.gigahard.ai
