apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: express
        image: node:18-alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create a directory for the Express server
          mkdir -p /app
          cd /app
          
          # Create package.json
          echo '{
            "name": "vibecode-express",
            "version": "1.0.0",
            "description": "Express server for GitHub OAuth callback",
            "main": "index.js",
            "dependencies": {
              "express": "^4.18.2",
              "cors": "^2.8.5"
            }
          }' > package.json
          
          # Create index.js
          echo 'const express = require("express");
          const cors = require("cors");
          const app = express();
          const port = process.env.PORT || 5000;

          // Enable CORS for all routes
          app.use(cors({
            origin: "*",
            methods: ["GET", "POST", "OPTIONS"],
            allowedHeaders: ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"],
            credentials: true
          }));

          console.log("Starting Express server...");

          // Simple route
          app.get("/", (req, res) => {
            res.send("Express server is running");
          });

          // Health check endpoint
          app.get("/health", (req, res) => {
            res.status(200).send("OK");
          });

          // GitHub OAuth callback endpoint
          app.get("/api/auth/github/exchange", (req, res) => {
            const code = req.query.code;
            console.log(`Received GitHub OAuth exchange request with code: ${code}`);
            
            // Return a mock response
            const mockResponse = {
              access_token: "mock_access_token",
              token_type: "bearer",
              user: {
                username: "mock_user",
                email: "mock_user@example.com",
                full_name: "Mock User",
                avatar_url: "https://example.com/avatar.png"
              }
            };
            
            console.log(`Returning mock response: ${JSON.stringify(mockResponse)}`);
            res.json(mockResponse);
          });

          // Start the server
          app.listen(port, "0.0.0.0", () => {
            console.log(`Express server running on port ${port}`);
          });' > index.js
          
          # Install dependencies
          npm install
          
          # Start the Express server
          node index.js
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-express
  namespace: vibecode
spec:
  selector:
    app: simple-express
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
