apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vibecode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: vibecode-frontend  # This is likely your container name
        image: gigahard/vibecode-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vibecode-github-oauth
              key: GITHUB_CLIENT_ID
        - name: API_URL
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vibecode
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
