apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibecode-db
  namespace: vibecode
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: "postgres:14"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: vibecode
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vibecode-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vibecode-db-credentials
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: vibecode-db-pvc
