apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vibecode-db-pvc
  namespace: vibecode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
