# traefik-values.yaml
deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  initContainers:
    - name: fix-acme-perms
      image: busybox:1.35
      command: ["sh", "-c", "chmod 600 /data/acme.json || true"]
      volumeMounts:
        - name: data
          mountPath: /data

ports:
  web:
    expose:
      default: true
    port: 80
    hostPort: 80
  websecure:
    expose:
      default: true
    port: 443
    hostPort: 443

certResolvers:
  letsencrypt:
    acme:
      email: your@email.com
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi
