deployment:
  kind: Deployment
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: vibecode2

ingressClass:
  enabled: true
  isDefaultClass: true

additionalArguments:
  - "--log.level=DEBUG"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--entrypoints.websecure.http.tls=true"

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: NodePort
  spec: {}
  nodePorts:
    web: 30080
    websecure: 30443

persistence:
  enabled: false
