deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

  podSecurityContext:
    fsGroup: 65532

  initContainers:
    - name: fix-permissions
      image: busybox:1.35
      command:
        - sh
        - -c
        - |
          touch /data/acme.json
          chmod 600 /data/acme.json
          chown 65532:65532 /data/acme.json
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: data  # <-- This must match Helm's expected volume name
          mountPath: /data

persistence:
  enabled: true
  existingClaim: traefik  # <-- This explicitly tells Helm to reuse your existing PVC named traefik

ports:
  web:
    expose:
      default: true
    port: 80
  websecure:
    expose:
      default: true
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
