# traefik-values.yaml
deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  # Remove all init containers and security contexts

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: longhorn

ports:
  web:
    port: 80
  websecure:
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
