# traefik-values.yaml
deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  initContainers:
    - name: fix-acme-perms
      image: busybox:1.35
      command:
        - sh
        - -c
        - |
          touch /data/acme.json
          chmod 600 /data/acme.json
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: traefik  # must match the actual PVC name
          mountPath: /data

persistence:
  enabled: true
  name: traefik  # same here
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi

ports:
  web:
    expose:
      default: true
    port: 80
  websecure:
    expose:
      default: true
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
