deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet

persistence:
  enabled: true
  name: traefik-cert
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi

ports:
  web:
    expose:
      default: true
    port: 80
  websecure:
    expose:
      default: true
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=you@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
