deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  podSecurityContext:
    fsGroup: 0            # Ensures the PVC is group-writable by Traefik
    runAsUser: 0          # Run the container as root user
    runAsGroup: 0         # Run the container as root group

persistence:
  enabled: true
  existingClaim: traefik  # Mounts Longhorn PVC "traefik" as "data" at /data

ports:
  web:
    expose:
      default: true
    port: 80
  websecure:
    expose:
      default: true
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
