# traefik-values.yaml
deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  initContainers:
    - name: fix-acme-perms
      image: busybox:1.35
      command: ["sh", "-c", "chmod 600 /data/acme.json || true"]
      volumeMounts:
        - name: data
          mountPath: /data

ports:
  web:
    expose:
      default: true
    port: 80
    hostPort: 80
  websecure:
    expose:
      default: true
    port: 443
    hostPort: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi
