deployment:
  kind: Deployment
  hostNetwork: true
  initContainers:
    - name: init-acme
      image: busybox:1.35
      command:
        - sh
        - -c
        - |
          mkdir -p /data
          touch /data/acme.json
          chmod 600 /data/acme.json
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      volumeMounts:
        - name: data
          mountPath: /data

securityContext:
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532

ingressClass:
  enabled: true
  isDefaultClass: true

additionalArguments:
  - "--log.level=DEBUG"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=admin@gigahard.ai"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

service:
  enabled: true
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

persistence:
  enabled: true
  path: /data
  size: 128Mi
  storageClass: longhorn
  existingClaim: traefik
