# traefik-values.yaml
additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"

persistence:
  enabled: true
  storageClass: longhorn
  accessMode: ReadWriteOnce
  size: 1Gi

deployment:
  initContainers:
    - name: fix-acme-perms
      image: busybox:1.35
      command: ["sh", "-c", "chmod 600 /data/acme.json || true"]
      volumeMounts:
        - name: data
          mountPath: /data
