deployment:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  podSecurityContext:
    fsGroup: 65532         # Use a non-root fsGroup for the Traefik container
    runAsUser: 65532       # Run the container as a non-root user (65532 is a typical non-root user in Kubernetes)
    runAsGroup: 65532      # Set the group as the same non-root user

persistence:
  enabled: true
  existingClaim: traefik  # Mounts Longhorn PVC "traefik" as "data" at /data

ports:
  web:
    expose:
      default: true
    port: 80
  websecure:
    expose:
      default: true
    port: 443

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
  - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
  - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
  - "--providers.kubernetesingress"
  - "--providers.kubernetescrd"

containers:
  - name: traefik
    image: traefik:v3.3.5
    securityContext:
      runAsUser: 65532       # Use non-root user (65532)
      runAsGroup: 65532      # Use non-root group (65532)
    volumeMounts:
      - mountPath: /data
        name: traefik

# Ensure the PVC (PersistentVolumeClaim) is not created as root and is accessible by non-root
volumeClaimTemplates: []
