# Production values for VibeCode

# Caddy configuration
caddy:
  image: docker.io/gigahard/vibecode-caddy:latest
  email: "your-actual-email@example.com"  # Update with your email for Let's Encrypt
  domain: "vibecode.gigahard.ai"
  tls:
    enabled: false  # Disable Caddy TLS since Traefik will handle it

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 80

# Disable ingress since we're using Traefik IngressRoute
ingress:
  enabled: false

# Cert-Manager configuration (using Traefik's built-in ACME support)
certManager:
  enabled: true
  issuer:
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "your-actual-email@example.com"  # Update with your email
  certificate:
    name: vibecode-tls
    secretName: vibecode-tls
    domain: vibecode.gigahard.ai

# Longhorn configuration
longhorn:
  enabled: true
  storageClass:
    name: "longhorn"
    isDefault: true

# GitHub OAuth configuration (update with your values)
github:
  clientId: ""
  clientSecret: ""
  redirectUri: "https://vibecode.gigahard.ai/auth/callback"

# Environment configuration
environment:
  name: production
