# Default values for VibeCode
# This is a YAML-formatted file.

# Common settings
nameOverride: ""
fullnameOverride: ""

# Image pull secrets
imagePullSecrets:
  - name: regcred

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: gigahard/vibecode-client
    tag: latest
    pullPolicy: Always
  port: 3000
  containerPort: 3000
  apiUrl: "/api"
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Express configuration
express:
  image: docker.io/gigahard/vibecode-express:latest
  pullPolicy: IfNotPresent
  port: 5000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# FastAPI configuration
fastapi:
  image: docker.io/gigahard/vibecode-fastapi:latest
  pullPolicy: IfNotPresent
  port: 8000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# GitHub OAuth configuration
github:
  # Credentials are managed via Kubernetes secrets
  clientId: ""
  clientSecret: ""
  redirectUri: "/auth/callback"

# Environment configuration
environment:
  # Can be "development", "staging", or "production"
  name: development

# Service configuration
service:
  type: ClusterIP

# Ingress configuration
ingress:
  host: vibecode.local

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Longhorn configuration
longhorn:
  enabled: false  # Disable Longhorn installation since it's already installed
  useExisting: true  # Use existing Longhorn installation
  storageClass: "longhorn"  # Name of the existing StorageClass

# Database configuration
database:
  name: vibecode
  username: postgres
  password: postgres  # Change this in production
  storage: 10Gi

# GitHub OAuth Configuration
github:
  clientId: "Iv23liWkm8qUlFlLAXKe"
  clientSecret: "3b5ecd0e5b9a6e7d879a6932cceba52ab71440c6"