# Production values for VibeCode

# Service configuration
service:
  type: ClusterIP

# Ingress configuration
ingress:
  enabled: true
  host: vibecode.gigahard.ai

# Longhorn configuration
longhorn:
  enabled: false  # Disable Longhorn installation since it's already installed
  useExisting: true  # Use existing Longhorn installation
  storageClass: "longhorn"  # Name of the existing StorageClass

# GitHub OAuth configuration
github:
  clientId: "Iv23liWkm8qUlFlLAXKe"    # Add the value from github_client_id.txt
  clientSecret: "3b5ecd0e5b9a6e7d879a6932cceba52ab71440c6"   # Add the value from github_client_secret.txt
  redirectUri: "https://vibecode.gigahard.ai/auth/callback"

# Environment configuration
environment:
  name: production

frontend:
  replicaCount: 1
  image:
    repository: gigahard/vibecode-client
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
  containerPort: 3000
  apiUrl: "/api"
 
# GitHub OAuth Configuration
github:
  clientId: "your-github-client-id"
  clientSecret: "your-github-client-secret"