# Default values for VibeCode
# This is a YAML-formatted file.

# Common settings
nameOverride: ""
fullnameOverride: ""

# Image pull secrets
imagePullSecrets:
  - name: regcred

# Caddy configuration
caddy:
  image: docker.io/gigahard/vibecode-caddy:latest
  pullPolicy: IfNotPresent
  ports:
    - 80
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  email: "your-email@example.com"  # For Let's Encrypt notifications
  domain: "vibecode.gigahard.ai"  # Your domain name
  tls:
    enabled: false  # Disable Caddy TLS since Traefik will handle it
  persistence:
    enabled: true
    size: 1Gi  # For storing certificates

# Frontend configuration
frontend:
  image: docker.io/gigahard/vibecode-client:latest
  pullPolicy: IfNotPresent
  port: 3000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Express configuration
express:
  image: docker.io/gigahard/vibecode-express:latest
  pullPolicy: IfNotPresent
  port: 5000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# FastAPI configuration
fastapi:
  image: docker.io/gigahard/vibecode-fastapi:latest
  pullPolicy: IfNotPresent
  port: 8000
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

# GitHub OAuth configuration
github:
  clientId: ""
  clientSecret: ""
  redirectUri: ""

# Environment configuration
environment:
  # Can be "development", "staging", or "production"
  name: development

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 80

# Ingress configuration (disabled in favor of Traefik IngressRoute)
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: vibecode.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Cert-Manager configuration (now using Traefik's built-in ACME support)
certManager:
  enabled: true
  issuer:
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "your-email@example.com"  # Update with your email
  certificate:
    name: vibecode-tls
    secretName: vibecode-tls
    domain: vibecode.gigahard.ai

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Longhorn configuration
longhorn:
  enabled: true
  storageClass:
    name: "longhorn"
    isDefault: true
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
      fsType: "ext4"
