# Production values for VibeCode

# Domain name
domain: "vibecode.gigahard.ai"

# Service configuration
service:
  type: ClusterIP

# Enable ingress for standard Kubernetes Ingress
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

# Longhorn configuration
longhorn:
  enabled: false  # Disable Longhorn installation since it's already installed
  useExisting: true  # Use existing Longhorn installation
  storageClass: "longhorn"  # Name of the existing StorageClass

# GitHub OAuth configuration (update with your values)
github:
  clientId: ""
  clientSecret: ""
  redirectUri: "https://vibecode.gigahard.ai/auth/callback"

# Environment configuration
environment:
  name: production
