# Production values for VibeCode

# Caddy configuration
caddy:
  image: docker.io/gigahard/vibecode-caddy:latest
  email: "your-actual-email@example.com"  # Update with your email for Let's Encrypt
  domain: "vibecode.gigahard.ai"
  tls:
    enabled: false  # Disable Caddy TLS since Traefik will handle it
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "longhorn"  # Use Longhorn StorageClass

# Service configuration
service:
  type: ClusterIP
  ports:
    http: 80

# Enable ingress for standard Kubernetes Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"

# Cert-Manager configuration
certManager:
  enabled: true
  issuer:
    name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "your-actual-email@example.com"  # Update with your email
  certificate:
    name: vibecode-tls
    secretName: vibecode-tls
    domain: vibecode.gigahard.ai

# Longhorn configuration
longhorn:
  enabled: true  # Enable Longhorn installation
  namespace: longhorn-system
  createNamespace: true
  persistence:
    defaultClass: true
    reclaimPolicy: Delete
    defaultClassReplicaCount: 3

# GitHub OAuth configuration (update with your values)
github:
  clientId: ""
  clientSecret: ""
  redirectUri: "https://vibecode.gigahard.ai/auth/callback"

# Environment configuration
environment:
  name: production
