# Production values for VibeCode

# Service configuration
service:
  type: ClusterIP

# Ingress configuration
ingress:
  host: vibecode.gigahard.ai

# Longhorn configuration
longhorn:
  enabled: false  # Disable Longhorn installation since it's already installed
  useExisting: true  # Use existing Longhorn installation
  storageClass: "longhorn"  # Name of the existing StorageClass

# GitHub OAuth configuration (update with your values)
github:
  clientId: ""
  clientSecret: ""
  redirectUri: "https://vibecode.gigahard.ai/auth/callback"

# Environment configuration
environment:
  name: production

frontend:
  port: 3000
