apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vibecode-tls
  namespace: kube-system
spec:
  secretName: vibecode-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vibecode.gigahard.ai
  dnsNames:
  - vibecode.gigahard.ai
