apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: default
data:
  traefik.yaml: |
    log:
      level: DEBUG
    entryPoints:
      web:
        address: ":80"
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
        http:
          tls:
            certResolver: letsencrypt
    certificatesResolvers:
      letsencrypt:
        acme:
          email: admin@gigahard.ai
          storage: /tmp/acme.json
          httpChallenge:
            entryPoint: web
          caServer: https://acme-v02.api.letsencrypt.org/directory
    providers:
      file:
        directory: /config
        watch: true
      kubernetesCRD:
        namespaces:
          - default
          - vibecode
      kubernetesIngress:
        namespaces:
          - default
          - vibecode 