apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {
      # Global options
      admin off
      # Disable automatic HTTPS since Traefik will handle it
      auto_https off
      # Trust the proxy protocol
      servers {
        protocol {
          allow_h2c
        }
      }
    }

    # Handle HTTP only since Traefik will handle HTTPS
    :80 {
      # Route to frontend
      handle_path / {
        reverse_proxy frontend:{{ .Values.frontend.port }}
      }

      # Route to Express API
      handle_path /api/express/* {
        uri strip_prefix /api/express
        reverse_proxy express:{{ .Values.express.port }}
      }

      # Route to FastAPI
      handle_path /api/* {
        uri strip_prefix /api
        reverse_proxy fastapi:{{ .Values.fastapi.port }}
      }

      # Health check
      handle /health {
        respond "OK" 200
      }

      # Log requests
      log {
        output stdout
        format console
      }
    }
