{{- if .Values.caddy.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.caddy.persistence.storageClass }}
  storageClassName: {{ .Values.caddy.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.caddy.persistence.size }}
{{- end }}
