apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
      {{- include "vibecode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: caddy
        {{- include "vibecode.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: caddy
          image: {{ .Values.caddy.image }}
          imagePullPolicy: {{ .Values.caddy.pullPolicy }}
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          resources:
            {{- toYaml .Values.caddy.resources | nindent 12 }}
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: caddy-data
              mountPath: /data
            - name: caddy-config-dir
              mountPath: /config
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: caddy-data
          emptyDir: {}
        - name: caddy-config-dir
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
