{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.issuer.name }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.certManager.issuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.certManager.issuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.certManager.issuer.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificate.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certManager.certificate.secretName }}
  issuerRef:
    name: {{ .Values.certManager.issuer.name }}
    kind: ClusterIssuer
  commonName: {{ .Values.certManager.certificate.domain }}
  dnsNames:
  - {{ .Values.certManager.certificate.domain }}
{{- end }}
