apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecode.fullname" . }}-db-credentials
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}