apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vibecode.fullname" . }}-db
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      {{- include "vibecode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: database
        {{- include "vibecode.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: "postgres:14"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "vibecode.fullname" . }}-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vibecode.fullname" . }}-db-credentials
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ include "vibecode.fullname" . }}-db-pvc