apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibecode.fullname" . }}-db
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: database
    {{- include "vibecode.selectorLabels" . | nindent 4 }}