apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vibecode.fullname" . }}-db-pvc
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.database.storage | default "10Gi" }}