apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: vibecode
  template:
    metadata:
      labels:
        app: caddy
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: vibecode
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.caddy.image }}
          imagePullPolicy: {{ .Values.caddy.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            {{- if .Values.caddy.persistence.enabled }}
            - name: caddy-data
              mountPath: /data
            {{- end }}
          resources:
            {{- toYaml .Values.caddy.resources | nindent 12 }}
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        {{- if .Values.caddy.persistence.enabled }}
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data
        {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: express
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: express
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-express
          image: {{ .Values.express.image }}
          imagePullPolicy: {{ .Values.express.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.express.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.express.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: fastapi
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: fastapi
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-fastapi
          image: {{ .Values.fastapi.image }}
          imagePullPolicy: {{ .Values.fastapi.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.fastapi.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
