{{- if .Values.express.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.express.replicas | default 1 }}
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: gigahard/vibecode-express:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-github-oauth
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-github-oauth
              key: GITHUB_CLIENT_SECRET
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-github-oauth
              key: JWT_SECRET
        - name: GITHUB_REDIRECT_URI
          value: {{ .Values.express.githubRedirectUri | quote }}
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-google-oauth
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-google-oauth
              key: GOOGLE_CLIENT_SECRET
        - name: GOOGLE_REDIRECT_URI
          value: {{ .Values.google.redirectUri | quote }}
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: express
{{- end }}
