apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
      {{- include "vibecode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: fastapi
        {{- include "vibecode.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.fastapi.image }}
          imagePullPolicy: {{ .Values.fastapi.pullPolicy }}
          ports:
            - containerPort: {{ .Values.fastapi.port }}
              protocol: TCP
              name: http
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: {{ .Values.fastapi.port | quote }}
            - name: GITHUB_CLIENT_ID
              value: {{ .Values.github.clientId | quote }}
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "vibecode.fullname" . }}-github-secret
                  key: client-secret
            - name: GITHUB_REDIRECT_URI
              value: {{ .Values.github.redirectUri | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment.name }}
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
