{{- if .Values.fastapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
  labels:
    app: {{ .Release.Name }}
    component: fastapi
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.fastapi.port }}
    targetPort: {{ .Values.fastapi.port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    component: fastapi
{{- end }} 