apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
        {{- include "vibecode.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-fastapi
          image: {{ .Values.fastapi.image }}
          imagePullPolicy: {{ .Values.fastapi.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.fastapi.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.fastapi.resources | nindent 12 }}
