apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: vibecode
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: vibecode-frontend
        image: gigahard/vibecode-client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: API_URL
          value: /api
        - name: VITE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vibecode-github-oauth
              key: GITHUB_CLIENT_ID
        - name: VITE_GITHUB_REDIRECT_URI
          value: "https://vibecode.gigahard.ai/github-callback"
        - name: VITE_GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "vibecode.fullname" . }}-google-oauth
              key: GOOGLE_CLIENT_ID
        - name: VITE_GOOGLE_REDIRECT_URI
          value: "https://vibecode.gigahard.ai/google-callback"
