apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecode.fullname" . }}-github-oauth
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_CLIENT_ID: {{ .Values.github.clientId | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.github.clientSecret | b64enc | quote }}