apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vibecode-ingress
  namespace: vibecode
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.priority: "100"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - vibecode.gigahard.ai
  rules:
    - host: vibecode.gigahard.ai
      http:
        paths:
          - path: /api/express
            pathType: Prefix
            backend:
              service:
                name: express
                port:
                  number: 5000
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: express
                port:
                  number: 5000
          - path: /github-callback
            pathType: Exact
            backend:
              service:
                name: express
                port:
                  number: 5000
          - path: /api/fastapi
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
