apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vibecode.fullname" . }}-github-secret
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
type: Opaque
data:
  # This is a placeholder. In production, you should use Helm's --set-file or a values file
  # that is not committed to version control to provide the actual secret.
  client-secret: {{ .Values.github.clientSecret | default "" | b64enc | quote }}
