apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.fastapi.port }}
      targetPort: {{ .Values.fastapi.port }}
      protocol: TCP
  selector:
    app: fastapi
