apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: express
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.express.port }}
      targetPort: {{ .Values.express.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: express
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.fastapi.port }}
      targetPort: {{ .Values.fastapi.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: fastapi
    app.kubernetes.io/instance: {{ .Release.Name }}
