apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=DEBUG"
      - "--certificatesresolvers.letsencrypt.acme.email={{ .Values.certManager.issuer.email }}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.caserver={{ .Values.certManager.issuer.server }}"
    
    ports:
      web:
        redirectTo: websecure
      
    ingressRoute:
      dashboard:
        enabled: true
