apiVersion: v1
kind: Service
metadata:
  name: {{ include "vibecode.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
    app.kubernetes.io/name: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary 