apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vibecode.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vibecode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "vibecode.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      labels:
        {{- include "vibecode.selectorLabels" . | nindent 8 }}
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: {{ .Values.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: POSTGRES_SERVER
              value: {{ include "vibecode.fullname" . }}-db
            - name: POSTGRES_USER
              value: {{ .Values.database.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }} 